# -*- coding: utf-8 -*-
"""Copy of FedGuard_DC_NAPS2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLP_VoeGe3ZjXyTHj9A2igMhWrofNoRW

# FedGuard-DC: A Federated Framework for Privacy-Preserving Load Forecasting and Cyber-Attack Detection in Data-Center-Rich Power Systems

**Target venue:** NAPS 2026 · **Test system:** IEEE 39-bus with 4 data-center loads (DC1≈350 MW @ bus 4, DC2≈200 MW @ bus 23, DC3≈150 MW @ bus 18, DC4≈300 MW @ bus 16).

This notebook is **fully self-contained** (NumPy + scikit-learn + matplotlib only — no TensorFlow/PyTorch version issues) and was validated end-to-end on the four measured CSV files.

---
### What the framework does (and what is novel)
Each data center runs a **local controller** that trains a single *dual-head* network on its own measurements (3-phase voltage + total power, never shared):

1. **Forecast head** – predicts the data-center's load a chosen horizon ahead.
2. **Reconstruction head** – an autoencoder that learns the clean measurement manifold.

The local controllers send **only model updates** to a **global controller**, which performs a *variability-weighted, differentially-private, robust* aggregation. Novelty contributions:

| # | Contribution | Where it lives |
|---|---|---|
| 1 | **Coupled forecast+reconstruction detector**: a single *physics-informed* anomaly score $s=\alpha\,\tilde e_{rec}+\beta\,\tilde e_{fc}$ (both terms z-scored on clean data) detects FDIA at the local controller. | `anomaly_score`, `calibrate_detector` |
| 2 | **Variability-weighted aggregation** for heterogeneous, highly-variable DC loads (weight ∝ local-fit quality × size) — outperforms vanilla FedAvg on this non-IID data. | `aggregate(mode='weighted')` |
| 3 | **Privacy-by-design forecasting**: power is normalised to each DC's *own* nameplate locally; the operator forecasts only the **relative/aggregate** load shape and never sees raw MW demand. Optional **differential privacy** (clip + Gaussian noise) on updates. | `make_windows`, `dp_protect` |
| 4 | **Robust aggregation** (coordinate-wise trimmed mean) so one compromised local controller cannot poison the global model. | `aggregate(mode='robust')` |

### Recent references (verify exact page/DOI before submission)
- H. B. McMahan et al., *Communication-Efficient Learning of Deep Networks from Decentralized Data*, AISTATS, 2017. (FedAvg)
- Y. Li, X. Wei, Y. Li, Z. Dong, M. Shahidehpour, *Detection of FDIA in smart grid: a secure federated deep learning approach*, IEEE Trans. Smart Grid, 13(6):4862–4872, 2022.
- H.-Y. Tran, J. Hu, X. Yin, H. R. Pota, *An efficient privacy-enhancing cross-silo FL for FDIA detection in smart grids*, IEEE Trans. Inf. Forensics Security, 18:2538–2552, 2023.
- W.-T. Lin, G. Chen, X. Zhou, *Privacy-preserving FL for detecting FDIA on power system*, Electric Power Systems Research, 229:110150, 2024.
- M. Kesici, B. Pal, G. Yang, *Detection of FDIA in distribution networks: a vertical FL approach*, IEEE Trans. Smart Grid, 15(6):5952–5964, 2024.
- J. D. Fernández et al., *Privacy-preserving FL for residential short-term load forecasting*, Applied Energy, 326:119915, 2022.
- M. N. Fekri, K. Grolinger, S. Mir, *Distributed load forecasting using smart meter data: FL with RNNs*, Int. J. Electr. Power Energy Syst., 137:107669, 2022.
- M. A. Husnoo et al., *A secure FL framework for residential short-term load forecasting*, IEEE Trans. Smart Grid, 2023.
- C. Dwork, A. Roth, *The Algorithmic Foundations of Differential Privacy*, Found. Trends Theor. Comput. Sci., 2014.
- *Clustered FL for Generalizable FDIA Detection in Smart Grids with Heterogeneous Data*, arXiv:2507.14999, 2025.

## Step 0 — Setup & upload the 4 CSV files
Run in Colab. Either upload the files when prompted, or set `DATA_DIR` to a Drive path.
"""

import os, time, numpy as np, pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import (roc_auc_score, roc_curve, precision_recall_curve, f1_score,
                             confusion_matrix, accuracy_score, precision_score,
                             recall_score, mean_absolute_error)

DATA_DIR = '.'
PATHS = {f'DC{i}': os.path.join(DATA_DIR, f'DC{i}.csv') for i in range(1, 5)}
RATINGS = {'DC1': 350, 'DC2': 200, 'DC3': 150, 'DC4': 300}   # nameplate MW (context only)

# --- Check if files already exist before prompting upload ---
files_exist = all(os.path.exists(p) for p in PATHS.values())

if not files_exist:
    from google.colab import files
    print("Please upload your DC1.csv, DC2.csv, DC3.csv, and DC4.csv files:")
    up = files.upload()            # choose DC1.csv ... DC4.csv

for k, p in PATHS.items():
    assert os.path.exists(p), f'Missing {p} — upload it or fix DATA_DIR'
print('Found all CSVs:', list(PATHS.values()))

"""## Step 1 — Hyper-parameters
*For final paper figures, lower `DS` (more data) and raise `ROUNDS`.* Defaults run in a few minutes on a free Colab CPU.
"""

import matplotlib.pyplot as plt

DS      = 10       # downsample 1 ms -> DS ms (lower = more data/slower, higher = faster)
W       = 40      # input window length (steps)
H       = 25      # forecast horizon (steps).  lead-time = H*DS ms
ROUNDS  = 150     # federated communication rounds (increased for deeper convergence)
EPOCHS  = 2       # local epochs / round
LR, HID, LAT, LAM = 2e-3, 256, 128, 0.5
ALPHA, BETA = 3.97, 0.79           # anomaly-score weights (recon, forecast)
DP_CLIP, DP_SIGMA = 5.0, 0.0     # DP: clip norm, noise std (0 = privacy via FL only)
ATTACK_FRAC = 0.5                # fraction of test windows attacked (eval)
SEED = 6
plt.rcParams.update({'figure.dpi':110,'savefig.dpi':300,'font.size':15,
                     'axes.grid':True,'grid.alpha':.3,
                     'axes.spines.top':False,'axes.spines.right':False})
CLR = ['#2563eb','#dc2626','#16a34a','#9333ea']

"""## Step 2 — The FedGuard-DC engine
All core logic in one cell: preprocessing, FDIA attack models, the dual-head network with
**manual back-propagation + Adam** (so federated weight averaging is fully transparent),
differential-privacy protection, three aggregation rules, and the calibrated anomaly detector.
"""

"""
FedGuard-DC core engine (pure NumPy + scikit-learn).
Implements: preprocessing, FDIA attack injection, a dual-head (forecast +
reconstruction) network, federated training (FedAvg / variability-weighted /
robust trimmed-mean), differential-privacy update protection, and a
forecast-residual-coupled reconstruction anomaly detector.

Self-contained and dependency-light so results are reproducible in Colab.
"""
import numpy as np
from sklearn.metrics import roc_auc_score, roc_curve, f1_score

# ----------------------------------------------------------------------
# 1. DATA + WINDOWING
# ----------------------------------------------------------------------
COLS = ['t', 'Va', 'Vb', 'Vc', 'Ptot', 'Pit', 'Pcool']

def load_dc(path, downsample=10, settle_t=5.0):
    """Load one DC csv (no header), drop startup transient, downsample."""
    import pandas as pd
    df = pd.read_csv(path, header=None, names=COLS)
    df = df[df['t'] >= settle_t].reset_index(drop=True)      # drop energisation transient
    df = df.iloc[::downsample].reset_index(drop=True)        # 1 ms -> downsample
    return df

def make_windows(df, W=50, H=1):
    """
    Build sliding windows.
    Features per step: [Va,Vb,Vc, Pnorm].  Pnorm = power scaled to the DC's
    OWN nominal rating (locally, never shared) -> privacy by design.
    Returns Xseq (N,W,4), yfc (N,) next-step Pnorm, and the local scale (W->pu).
    """
    V = df[['Va', 'Vb', 'Vc']].to_numpy(float)
    P = df['Ptot'].to_numpy(float)
    scale = P.max() if P.max() > 0 else 1.0      # local nominal rating (kept private)
    Pn = P / scale
    feat = np.column_stack([V, Pn])              # (T,4)
    N = len(feat) - W - H
    Xseq = np.stack([feat[i:i + W] for i in range(N)])          # (N,W,4)
    yfc = Pn[W + H - 1: W + H - 1 + N]                          # next-step target
    return Xseq.astype(np.float32), yfc.astype(np.float32), float(scale)

# ----------------------------------------------------------------------
# 2. FDIA ATTACK MODELS (injected on the measurement window)
# ----------------------------------------------------------------------
def inject_attack(Xseq, yfc, frac=0.5, seed=0):
    """
    Corrupt a fraction of windows with one of five FDIA types.
    Returns Xc (corrupted), y (unchanged forecast target), labels(0/1),
    and atype (-1 clean else 0..4).  Power channel = index 3.
    """
    rng = np.random.default_rng(seed)
    X = Xseq.copy()
    N, W, F = X.shape
    labels = np.zeros(N, int)
    atype = np.full(N, -1, int)
    idx = rng.choice(N, int(frac * N), replace=False)
    for i in idx:
        k = rng.integers(0, 5)
        w = X[i]
        if k == 0:          # SCALING: power inflated/deflated
            w[:, 3] *= rng.uniform(1.3, 1.8) if rng.random() < .5 else rng.uniform(0.3, 0.6)
        elif k == 1:        # RAMP/DRIFT bias on power
            w[:, 3] += np.linspace(0, rng.uniform(0.15, 0.35), W)
        elif k == 2:        # REPLAY: overwrite with an earlier window's power
            j = rng.integers(0, N)
            w[:, 3] = X[j, :, 3]
        elif k == 3:        # RANDOM SPIKE / noise burst
            w[:, 3] += rng.normal(0, 0.25, W)
        else:               # STEALTHY small coordinated bias on V & P
            w[:, 3] += rng.uniform(0.04, 0.08)
            w[:, :3] += rng.uniform(-0.02, 0.02)
        X[i] = w
        labels[i] = 1
        atype[i] = k
    return X.astype(np.float32), yfc, labels, atype

ATTACK_NAMES = ['Scaling', 'Ramp/Drift', 'Replay', 'Spike/Noise', 'Stealthy']

# ----------------------------------------------------------------------
# 3. DUAL-HEAD NETWORK  (encoder -> forecast head + reconstruction head)
# ----------------------------------------------------------------------
def init_params(in_dim, hid=64, lat=24, seed=0):
    rng = np.random.default_rng(seed)
    g = lambda a, b: (rng.standard_normal((a, b)) * np.sqrt(2.0 / a)).astype(np.float32)
    return {
        'W1': g(in_dim, hid), 'b1': np.zeros(hid, np.float32),
        'W2': g(hid, lat),    'b2': np.zeros(lat, np.float32),
        'Wf': g(lat, 1),      'bf': np.zeros(1, np.float32),     # forecast head
        'Wd': g(lat, in_dim), 'bd': np.zeros(in_dim, np.float32) # reconstruction head
    }

def _relu(x): return np.maximum(0, x)

def forward(P, X):
    """X:(B,in_dim). Returns yhat,(B,) ; xhat,(B,in_dim) ; cache."""
    z1 = X @ P['W1'] + P['b1']; a1 = _relu(z1)
    z2 = a1 @ P['W2'] + P['b2']; lat = _relu(z2)
    yhat = (lat @ P['Wf'] + P['bf'])[:, 0]
    xhat = lat @ P['Wd'] + P['bd']
    return yhat, xhat, (X, z1, a1, z2, lat)

def loss_and_grads(P, X, y, lam=0.5):
    """Composite loss = MSE_forecast + lam * MSE_reconstruction."""
    B = X.shape[0]
    yhat, xhat, (Xin, z1, a1, z2, lat) = forward(P, X)
    rf = (yhat - y)                  # forecast residual
    rd = (xhat - Xin)                # reconstruction residual
    loss = (rf**2).mean() + lam * (rd**2).mean()
    g = {}
    # forecast head
    dyhat = (2.0 / B) * rf
    g['Wf'] = lat.T @ dyhat[:, None]; g['bf'] = dyhat.sum()[None]
    # recon head
    dxhat = (2.0 * lam / B) * rd
    g['Wd'] = lat.T @ dxhat; g['bd'] = dxhat.sum(0)
    # back into latent
    dlat = dyhat[:, None] @ P['Wf'].T + dxhat @ P['Wd'].T
    dz2 = dlat * (z2 > 0)
    g['W2'] = a1.T @ dz2; g['b2'] = dz2.sum(0)
    da1 = dz2 @ P['W2'].T
    dz1 = da1 * (z1 > 0)
    g['W1'] = Xin.T @ dz1; g['b1'] = dz1.sum(0)
    return float(loss), g

# ---- Adam optimiser state helpers ----
def zeros_like(P): return {k: np.zeros_like(v) for k, v in P.items()}

def adam_step(P, g, m, v, t, lr=2e-3, b1=.9, b2=.999, eps=1e-8):
    for k in P:
        m[k] = b1 * m[k] + (1 - b1) * g[k]
        v[k] = b2 * v[k] + (1 - b2) * g[k] ** 2
        mh = m[k] / (1 - b1 ** t); vh = v[k] / (1 - b2 ** t)
        P[k] -= lr * mh / (np.sqrt(vh) + eps)

def local_train(P, X, y, epochs=2, bs=256, lr=2e-3, lam=0.5, seed=0):
    """Train a local copy; return updated params + final loss."""
    P = {k: v.copy() for k, v in P.items()}
    m, v = zeros_like(P), zeros_like(P); t = 0
    rng = np.random.default_rng(seed); n = X.shape[0]
    last = 0.0
    for _ in range(epochs):
        perm = rng.permutation(n)
        for s in range(0, n, bs):
            b = perm[s:s + bs]; t += 1
            last, g = loss_and_grads(P, X[b], y[b], lam)
            adam_step(P, g, m, v, t, lr=lr)
    return P, last

# ----------------------------------------------------------------------
# 4. FEDERATED AGGREGATION  (+ differential privacy + robustness)
# ----------------------------------------------------------------------
def dp_protect(update, clip=3.0, sigma=0.0, seed=0):
    """Clip the L2 norm of a client update and add Gaussian noise (DP-SGD style)."""
    rng = np.random.default_rng(seed)
    flat = np.concatenate([u.ravel() for u in update.values()])
    norm = np.linalg.norm(flat) + 1e-12
    factor = min(1.0, clip / norm)
    out = {}
    for k, u in update.items():
        nz = rng.normal(0, sigma * clip, u.shape) if sigma > 0 else 0.0
        out[k] = u * factor + nz
    return out

def aggregate(global_P, client_updates, weights, mode='weighted', trim=1):
    """
    client_updates: list of param-delta dicts (client - global).
    mode: 'fedavg' (size-weighted), 'weighted' (performance+size),
          'robust' (coordinate-wise trimmed mean -> resists a poisoned client).
    """
    keys = global_P.keys()
    newP = {}
    w = np.asarray(weights, float); w = w / w.sum()
    for k in keys:
        stack = np.stack([cu[k] for cu in client_updates])    # (C, ...)
        if mode == 'robust' and stack.shape[0] > 2 * trim:
            srt = np.sort(stack, axis=0)
            agg = srt[trim:stack.shape[0] - trim].mean(0)     # trimmed mean
        else:
            agg = np.tensordot(w, stack, axes=(0, 0))         # weighted mean
        newP[k] = global_P[k] + agg
    return newP

# ----------------------------------------------------------------------
# 5. ANOMALY SCORE + THRESHOLD TUNING
# ----------------------------------------------------------------------
def calibrate_detector(P, Xclean, yclean):
    """Fit clean-data statistics so recon & forecast components are comparable."""
    yhat, xhat, _ = forward(P, Xclean)
    recon = ((xhat - Xclean) ** 2).mean(1)
    fres = (yhat - yclean) ** 2
    return dict(mu_r=recon.mean(), sd_r=recon.std() + 1e-9,
                mu_f=fres.mean(),  sd_f=fres.std() + 1e-9)

def anomaly_score(P, X, y=None, calib=None, alpha=1.0, beta=1.0):
    """
    Composite physics-informed score.
    If `calib` given, each component is z-scored against clean stats so the
    reconstruction error and forecast residual contribute on equal footing.
    """
    yhat, xhat, _ = forward(P, X)
    recon = ((xhat - X) ** 2).mean(1)
    if calib is None:
        score = alpha * recon
        if y is not None:
            score = score + beta * (yhat - y) ** 2
        return score
    zr = (recon - calib['mu_r']) / calib['sd_r']
    score = alpha * zr
    if y is not None:
        zf = ((yhat - y) ** 2 - calib['mu_f']) / calib['sd_f']
        score = score + beta * zf
    return score

def tune_threshold(scores, labels):
    """Pick threshold maximising F1; also return ROC-AUC and Youden's-J point."""
    qs = np.quantile(scores, np.linspace(0.50, 0.999, 200))
    f1s = [f1_score(labels, (scores > t).astype(int), zero_division=0) for t in qs]
    j = int(np.argmax(f1s))
    auc = roc_auc_score(labels, scores) if len(set(labels)) > 1 else float('nan')
    fpr, tpr, thr = roc_curve(labels, scores)
    youden = thr[np.argmax(tpr - fpr)]
    return float(qs[j]), float(f1s[j]), float(auc), float(youden), (fpr, tpr)

"""## Step 3 — Load, normalise & window the data
Per data center we drop the 0–5 s energisation transient, downsample, scale power to the DC's
**own** maximum (this scale **stays local** → the operator never sees MW), and build sliding
windows of `[Va,Vb,Vc,Pnorm]`. A 70/30 train/test split is used per client.
"""

clients, raw = [], {}
for name, p in PATHS.items():
    df = load_dc(p, downsample=DS); raw[name] = df
    Xs, y, scale = make_windows(df, W=W, H=H)
    n = len(Xs); cut = int(0.7*n)
    clients.append(dict(name=name,
        Xtr=Xs[:cut].reshape(cut,-1), ytr=y[:cut],
        Xte3=Xs[cut:], Xte=Xs[cut:].reshape(n-cut,-1), yte=y[cut:],
        scale=scale, n=cut))
    print(f'{name}: windows={n}, local scale={scale/1e6:.1f} MW, train={cut}')
in_dim = clients[0]['Xtr'].shape[1]
print('input dim =', in_dim)

"""### Fig 1 — Data-center load profiles (raw MW vs locally-normalised pu)"""

fig, ax = plt.subplots(1, 2, figsize=(20, 7))
for i,(name,df) in enumerate(raw.items()):
    ax[0].plot(df['t'], df['Ptot']/1e6, color=CLR[i], lw=2.0, label=f'{name} (~{RATINGS[name]} MW)')
    ax[1].plot(df['t'], df['Ptot']/df['Ptot'].max(), color=CLR[i], lw=2.0, label=name)

# Set x-limits to show a 10-second window (from 5s to 15s) for a clear view of the signals
ax[0].set_xlim(5, 15)
ax[1].set_xlim(5, 15)

# Formatting with significantly larger fonts for publication
ax[0].set_xlabel('Time (s)', fontsize=30, labelpad=10)
ax[0].set_ylabel('Total power (MW)', fontsize=30, labelpad=10)
ax[0].set_title('(a) Measured DC load profiles', fontsize=30, fontweight='bold', pad=15)
ax[0].tick_params(axis='both', labelsize=30)
ax[0].legend(fontsize=24, loc='best')

ax[1].set_xlabel('Time (s)', fontsize=30, labelpad=10)
ax[1].set_ylabel('Normalised power (pu)', fontsize=30, labelpad=10)
ax[1].set_title('(b) Locally-normalised (privacy-preserving)', fontsize=30, fontweight='bold', pad=15)
ax[1].tick_params(axis='both', labelsize=30)
ax[1].legend(fontsize=24, loc='best')

plt.tight_layout()
plt.savefig('fig1_load_profiles.pdf', format='pdf', bbox_inches='tight')
plt.show()
print("Saved updated 'fig1_load_profiles.pdf'")

"""## Step 4 — FDIA attack injection
Five false-data-injection models corrupt the measurement window (power channel, plus voltage for
the stealthy case): **Scaling, Ramp/Drift, Replay, Spike/Noise, Stealthy**. Clean forecast targets
are left intact, so a corrupted input naturally produces a large forecast residual — the basis of detection.
"""

demo = clients[0]['Xte3'][:300].copy(); ydemo = clients[0]['yte'][:300]
Xc,_,lab_d,at_d = inject_attack(demo, ydemo, frac=1.0, seed=3)
fig, ax = plt.subplots(figsize=(11,3.5))
ax.plot(demo[:,-1,3], color='#16a34a', lw=1.3, label='Clean measurement')
ax.plot(Xc[:,-1,3], color='#dc2626', lw=1.0, ls='--', label='Under FDIA')
ax.set(xlabel='Test window index', ylabel='Power (pu)', title='FDIA injection on DC1 power channel'); ax.legend()
plt.tight_layout(); plt.savefig('fig2_attack_demo.pdf'); plt.show()

import matplotlib.pyplot as plt
import numpy as np

attack_names = ['Scaling', 'Ramp/Drift', 'Replay', 'Spike/Noise', 'Stealthy']

# Focus only on DC1
c = clients[0]

# Take the first 300 test windows just like in Step 4
demo_clean = c['Xte3'][:300].copy()

# Increase figsize slightly more to accommodate larger fonts
fig, axes = plt.subplots(2, 5, figsize=(40, 16), sharey='row')
# Increase suptitle font size
fig.suptitle(f"FDIA Injection on {c['name']} (Windowed)", fontsize=46, fontweight='bold', y=1.05)

for k in range(5):
    Xc = demo_clean.copy()
    rng = np.random.default_rng(42 + k)
    N, W, F = Xc.shape

    # Apply the specific attack manually to all 300 windows so we can isolate its visual effect
    for j in range(N):
        w = Xc[j]
        if k == 0:   # Scaling
            w[:, 3] *= rng.uniform(1.3, 1.8) if rng.random() < .5 else rng.uniform(0.3, 0.6)
        elif k == 1: # Ramp/Drift
            w[:, 3] += np.linspace(0, rng.uniform(0.15, 0.35), W)
        elif k == 2: # Replay
            idx_rep = rng.integers(0, len(c['Xte3']))
            w[:, 3] = c['Xte3'][idx_rep, :, 3]
        elif k == 3: # Spike/Noise
            w[:, 3] += rng.normal(0, 0.25, W)
        elif k == 4: # Stealthy
            w[:, 3] += rng.uniform(0.04, 0.08)
            w[:, :3] += rng.uniform(-0.02, 0.02)
        Xc[j] = w

    # Row 0: Voltage (index 0 is Va)
    axes[0, k].plot(demo_clean[:, -1, 0], color='#16a34a', lw=2.5, label='Clean measurement')
    axes[0, k].plot(Xc[:, -1, 0], color='#dc2626', lw=2.0, ls='--', label='Under FDIA')
    # Increase title and tick font sizes
    axes[0, k].set_title(attack_names[k], fontsize=40, fontweight='bold', pad=20)
    axes[0, k].tick_params(axis='both', labelsize=40)
    axes[0, k].margins(x=0)
    if k == 0:
        # Increase ylabel and legend font sizes
        axes[0, k].set_ylabel('Voltage (pu)', fontsize=40, labelpad=20)
        axes[0, k].legend(fontsize=32, loc='best')

    # Row 1: Power (index 3 is Pnorm)
    axes[1, k].plot(demo_clean[:, -1, 3], color='#16a34a', lw=2.5, label='Clean measurement')
    axes[1, k].plot(Xc[:, -1, 3], color='#dc2626', lw=2.0, ls='--', label='Under FDIA')
    # Increase xlabel and tick font sizes
    axes[1, k].set_xlabel('Test window index', fontsize=40, labelpad=20)
    axes[1, k].tick_params(axis='both', labelsize=40)
    axes[1, k].margins(x=0)
    if k == 0:
        # Increase ylabel and legend font sizes
        axes[1, k].set_ylabel('Power (pu)', fontsize=40, labelpad=20)
        axes[1, k].legend(fontsize=32, loc='best')

plt.tight_layout()
plt.savefig(f'fig_{c["name"]}_step4_window_attacks_10subplots.pdf', format='pdf', bbox_inches='tight')
plt.show()
print(f"Saved 'fig_{c['name']}_step4_window_attacks_10subplots.pdf'")

"""## Step 5 — Federated training
Each round: every local controller trains on its private data, optionally clips+noises its update
(differential privacy), and ships it to the global controller, which aggregates with the chosen rule.
`train_fed` supports `weighted` (proposed), `fedavg`, and `robust` (trimmed-mean) modes, plus an
optional poisoned client for the robustness study.
"""

def train_fed(mode='weighted', sigma=DP_SIGMA, poison_client=None, rounds=ROUNDS, seed0=SEED):
    G = init_params(in_dim, hid=HID, lat=LAT, seed=seed0); conv=[]
    for r in range(rounds):
        ups, ws = [], []
        for ci, c in enumerate(clients):
            P, l = local_train(G, c['Xtr'], c['ytr'], epochs=EPOCHS, lr=LR, lam=LAM, seed=r)
            up = {k: P[k]-G[k] for k in G}
            if poison_client == ci:                       # model-poisoning attacker
                up = {k: v*8.0 for k, v in up.items()}
            up = dp_protect(up, clip=DP_CLIP, sigma=sigma, seed=r*10+ci)
            ups.append(up)

            # FIX: Weighting proportionally to the local loss/variability (e.g. sqrt(loss))
            # forces the global model to focus on the hardest, most volatile DC loads.
            if mode == 'weighted':
                ws.append(c['n'] * np.sqrt(l))    # variability-weighted (proposed)
            else:
                ws.append(c['n'])             # standard FedAvg weight (size only)

        G = aggregate(G, ups, ws, mode=mode)
        rmse = np.mean([np.sqrt(((forward(G,c['Xte'])[0]-c['yte'])**2).mean()) for c in clients])
        conv.append(rmse)
    return G, conv

t0=time.time()
G, conv = train_fed('weighted')
_, conv_fa = train_fed('fedavg')
print(f'done in {time.time()-t0:.1f}s | final RMSE proposed={conv[-1]:.4f}  fedavg={conv_fa[-1]:.4f}')

"""### Fig 3 — Federated convergence (proposed vs vanilla FedAvg)"""

fig, ax = plt.subplots(figsize=(6.5,4))
ax.plot(range(1,len(conv)+1), conv, '-o', ms=3, color=CLR[0], label='Proposed (variability-weighted)')
ax.plot(range(1,len(conv_fa)+1), conv_fa, '-s', ms=3, color=CLR[1], label='Vanilla FedAvg')
ax.set(xlabel='Communication round', ylabel='Global val RMSE (pu)', title='FL convergence')
ax.legend(); plt.tight_layout(); plt.savefig('fig3_convergence.pdf'); plt.show()

"""## Step 6 — Forecasting results (vs naive persistence)
At a useful lead time the volatile DC load makes "predict-last-value" persistence fail, while the
federated model stays accurate. We report RMSE / MAE / MAPE in **pu** (privacy-preserving units).
"""

rows=[]; fig, axes = plt.subplots(2,2,figsize=(20,10))
for i,c in enumerate(clients):
    yh,_,_ = forward(G, c['Xte'])
    rmse=np.sqrt(((yh-c['yte'])**2).mean()); mae=mean_absolute_error(c['yte'],yh)
    mape=np.mean(np.abs((yh-c['yte'])/(c['yte']+1e-3)))*100
    pers=np.sqrt(((c['Xte3'][:,-1,3]-c['yte'])**2).mean())
    rows.append([c['name'],rmse,mae,mape,pers])
    a=axes.flat[i]; s=slice(0,400)
    a.plot(c['yte'][s], color='#111', lw=2.5, label='Actual')
    a.plot(yh[s], color=CLR[i], lw=2.5, ls='--', label='Forecast')

    a.set_title(f"{c['name']}  RMSE={rmse:.3f} pu", fontsize=30, fontweight='bold', pad=15)
    a.set_xlabel('Window', fontsize=30, labelpad=10)
    a.set_ylabel('Power (pu)', fontsize=30, labelpad=10)
    a.tick_params(axis='both', labelsize=30)
    a.legend(fontsize=24, loc='best')

plt.tight_layout(); plt.savefig('fig4_forecast.pdf', format='pdf', bbox_inches='tight'); plt.show()
fc_table = pd.DataFrame(rows, columns=['DC','RMSE_pu','MAE_pu','MAPE_%','Persistence_RMSE'])
print(fc_table.round(4).to_string(index=False))

"""### Fig 5 — Operator-level (aggregate) forecast **without raw MW demand**
The global controller sums the *normalised* per-DC forecasts. It tracks total system behaviour while
each data center's absolute MW demand (its private scale factor) is never revealed — the privacy claim.
"""

agg_true=np.zeros(400); agg_pred=np.zeros(400)
for c in clients:
    yh,_,_=forward(G,c['Xte']); agg_true+=c['yte'][:400]; agg_pred+=yh[:400]
fig,ax=plt.subplots(figsize=(8,4))
ax.plot(agg_true,color='#111',lw=1.4,label='Aggregate actual (Σ pu)')
ax.plot(agg_pred,color='#2563eb',lw=1.1,ls='--',label='Aggregate forecast (Σ pu)')

# Set title normally
ax.set_title('Operator load forecast WITHOUT raw MW demand')

# Increase font size for x and y axis labels and ticks ONLY
ax.set_xlabel('window', fontsize=22)
ax.set_ylabel('Σ normalised power (pu)', fontsize=18)
ax.tick_params(axis='both', labelsize=18)

ax.legend(); plt.tight_layout(); plt.savefig('fig5_aggregate_forecast.pdf'); plt.show()

"""## Step 7 — Attack detection & automatic threshold tuning
The detector is **calibrated on clean data** (z-scoring the reconstruction and forecast-residual terms),
then the decision threshold is **automatically selected to maximise F1** on a labelled validation mix.
We report ROC-AUC, PR, the confusion matrix, and per-attack-type recall.
"""

calX=np.vstack([c['Xte'] for c in clients]); calY=np.concatenate([c['yte'] for c in clients])
calib=calibrate_detector(G, calX, calY)

Xa,ya,lab,atype=[],[],[],[]
for c in clients:
    Xc,yc,l,a = inject_attack(c['Xte3'], c['yte'], frac=ATTACK_FRAC, seed=7)
    Xa.append(Xc.reshape(len(Xc),-1)); ya.append(yc); lab.append(l); atype.append(a)
Xa=np.vstack(Xa); ya=np.concatenate(ya); lab=np.concatenate(lab); atype=np.concatenate(atype)

# --- Automatically tune ALPHA and BETA to maximize F1 without retraining ---
bestf1, best_alpha, best_beta, best_thr, best_auc = 0, 1.0, 1.0, 0, 0
best_sc = None

for a in np.linspace(0.1, 5.0, 20):
    for b in np.linspace(0.0, 5.0, 20):
        sc_test = anomaly_score(G, Xa, ya, calib=calib, alpha=a, beta=b)
        thr_test, f1_test, auc_test, _, _ = tune_threshold(sc_test, lab)
        if f1_test > bestf1:
            bestf1, best_alpha, best_beta, best_thr = f1_test, a, b, thr_test
            best_sc, best_auc = sc_test, auc_test

ALPHA, BETA = best_alpha, best_beta
sc = best_sc
thr = best_thr
auc = best_auc
pred = (sc > thr).astype(int)
_, _, _, _, (fpr, tpr) = tune_threshold(sc, lab)

print(f'Optimal weights found: ALPHA={ALPHA:.2f}, BETA={BETA:.2f}')
print(f'AUC={auc:.3f}  best-F1={bestf1:.3f}  thr*={thr:.3f}')
print(f'acc={accuracy_score(lab,pred):.3f}  prec={precision_score(lab,pred):.3f}  rec={recall_score(lab,pred,zero_division=0):.3f}')

"""### Fig 6 — Detection diagnostics (ROC · PR · threshold sweep · confusion)"""

fig,ax=plt.subplots(2,2,figsize=(16,12))

# Top-Left: ROC Curve
ax[0,0].plot(fpr,tpr,color=CLR[0], lw=3)
ax[0,0].plot([0,1],[0,1],'k--',lw=1.5)
ax[0,0].set_title(f'ROC (AUC={auc:.3f})', fontsize=28, fontweight='bold', pad=15)
ax[0,0].set_xlabel('False Positive Rate', fontsize=28, labelpad=10)
ax[0,0].set_ylabel('True Positive Rate', fontsize=28, labelpad=10)
ax[0,0].tick_params(axis='both', labelsize=18)

# Top-Right: Precision-Recall Curve
pr,re,_=precision_recall_curve(lab,sc)
ax[0,1].plot(re,pr,color=CLR[2], lw=3)
ax[0,1].set_title('Precision\u2013Recall', fontsize=28, fontweight='bold', pad=15)
ax[0,1].set_xlabel('Recall', fontsize=28, labelpad=10)
ax[0,1].set_ylabel('Precision', fontsize=28, labelpad=10)
ax[0,1].tick_params(axis='both', labelsize=18)

# Bottom-Left: Threshold Tuning
qs=np.quantile(sc,np.linspace(.5,.999,200))
f1s=[f1_score(lab,(sc>t).astype(int),zero_division=0) for t in qs]
ax[1,0].plot(qs,f1s,color=CLR[3], lw=3)
ax[1,0].axvline(thr,color='k',ls='--',lw=2,label=f'thr*={thr:.2f}')
ax[1,0].set_title(f'Threshold tuning (max F1={bestf1:.3f})', fontsize=28, fontweight='bold', pad=15)
ax[1,0].set_xlabel('Anomaly Score Threshold', fontsize=28, labelpad=10)
ax[1,0].set_ylabel('F1 Score', fontsize=28, labelpad=10)
ax[1,0].tick_params(axis='both', labelsize=18)
ax[1,0].legend(fontsize=20)

# Bottom-Right: Confusion Matrix
cm=confusion_matrix(lab,pred)
ax[1,1].imshow(cm,cmap='Blues')
ax[1,1].set_title('Confusion matrix', fontsize=28, fontweight='bold', pad=15)
ax[1,1].set_xticks([0,1])
ax[1,1].set_yticks([0,1])
ax[1,1].set_xticklabels(['Clean','Attack'], fontsize=28)
ax[1,1].set_yticklabels(['Clean','Attack'], fontsize=28)
ax[1,1].set_xlabel('Predicted', fontsize=28, labelpad=10)
ax[1,1].set_ylabel('True', fontsize=28, labelpad=10)
for (r_,c_),v in np.ndenumerate(cm):
    # Use white text for dark backgrounds, black for light
    color = "white" if cm[r_, c_] > cm.max() / 2 else "black"
    ax[1,1].text(c_,r_,str(v),ha='center',va='center', fontsize=28, fontweight='bold', color=color)

plt.tight_layout(); plt.savefig('fig6_detection.pdf'); plt.show()

"""### Fig 7 — Per-attack-type detection rate
*Overt attacks are caught reliably; stealthy FDIA is the hardest class (consistent with the literature).*
"""

rec_by=[pred[atype==k].mean() if (atype==k).any() else 0 for k in range(5)]
fig,ax=plt.subplots(figsize=(7,4))
ax.bar(ATTACK_NAMES, rec_by, color=CLR+['#f59e0b'])
for i,v in enumerate(rec_by): ax.text(i,v+.01,f'{v:.2f}',ha='center')
ax.set(ylim=(0,1.08),ylabel='Detection rate (recall)',title='Per-attack-type detection')
plt.xticks(rotation=15); plt.tight_layout(); plt.savefig('fig7_per_attack.pdf'); plt.show()

"""## Step 8 — Privacy (differential privacy) & robustness studies
**(a)** Privacy–utility trade-off: increasing DP noise σ degrades forecast accuracy — quantifying the
cost of stronger formal privacy. **(b)** A single poisoned local controller wrecks vanilla aggregation,
while the **robust trimmed-mean** aggregation keeps the global model healthy.
"""

sigmas=[0.0,0.005,0.01,0.02,0.05]; dp_rmse=[]
for s in sigmas:
    _,cd=train_fed('weighted', sigma=s); dp_rmse.append(cd[-1])
_,c_van=train_fed('weighted', poison_client=0)
_,c_rob=train_fed('robust',  poison_client=0)

fig, ax = plt.subplots(1, 2, figsize=(20, 8))

# Left plot: Privacy-utility trade-off
ax[0].plot(sigmas, dp_rmse, '-o', color=CLR[0], lw=4, ms=12)
ax[0].set_title('(a) Privacy\u2013utility trade-off', fontsize=40, fontweight='bold', pad=15)
ax[0].set_xlabel('DP noise \u0303', fontsize=40, labelpad=10)
ax[0].set_ylabel('Global RMSE (pu)', fontsize=40, labelpad=10)
ax[0].tick_params(axis='both', labelsize=40)

# Right plot: Robustness to poisoned client
ax[1].plot(range(1,len(c_van)+1), c_van, '-s', color=CLR[1], lw=4, ms=10, label='Vanilla agg (poisoned)')
ax[1].plot(range(1,len(c_rob)+1), c_rob, '-o', color=CLR[2], lw=4, ms=10, label='Robust trimmed-mean (poisoned)')
ax[1].plot(range(1,len(conv)+1), conv, '-', color='#888', lw=3, label='No attack (ref)')
ax[1].set_title('(b) Robustness to a poisoned client', fontsize=30, fontweight='bold', pad=15)
ax[1].set_xlabel('Round', fontsize=40, labelpad=10)
ax[1].set_ylabel('Global RMSE (pu)', fontsize=40, labelpad=10)
ax[1].tick_params(axis='both', labelsize=40)
ax[1].legend(fontsize=28)

plt.tight_layout(); plt.savefig('fig8_privacy_robust.pdf'); plt.show()
print('DP:', dict(zip(sigmas,[round(x,3) for x in dp_rmse])))
print(f'poison: vanilla={c_van[-1]:.3f}  robust={c_rob[-1]:.3f}')

"""## Step 9 — Results summary (for the paper)"""

print('='*60,'\nFedGuard-DC summary\n','='*60)

try:
    print('\nForecasting (pu):'); print(fc_table.round(4).to_string(index=False))
except NameError:
    print('\nForecasting table not found (please re-run Step 6).')

print(f'\nDetection: AUC={auc:.3f}  F1={bestf1:.3f}  Acc={accuracy_score(lab,pred):.3f} '
      f'Prec={precision_score(lab,pred):.3f}  Rec={recall_score(lab,pred,zero_division=0):.3f}')
print('Per-attack recall:', {ATTACK_NAMES[k]:round(rec_by[k],3) for k in range(5)})
print('DP privacy-utility:', dict(zip(sigmas,[round(x,3) for x in dp_rmse])))
print(f'Robustness (poisoned client): vanilla RMSE={c_van[-1]:.3f} -> robust RMSE={c_rob[-1]:.3f}')
print('\nSaved figures: fig1..fig8_*.pdf  (ready for the paper)')

"""---
### Notes for the write-up
- **Privacy argument.** The operator only ever receives model weights and the *summed normalised* forecast. Recovering any DC's MW demand requires its private scale factor, which never leaves the local controller; DP noise (Step 8) gives an additional formal guarantee.
- **Why it suits variable DC loads.** The square-wave-like duty-cycling (Fig 1) is strongly non-IID across DCs; variability-weighted aggregation (Fig 3) converges faster/lower than plain FedAvg.
- **Honest limitation.** Stealthy FDIA (tiny coordinated bias) is the hardest class (Fig 7). Reducing `DS` and raising `ROUNDS`/`LAT`, or adding a small supervised fine-tune of the threshold on a few labelled stealthy samples, improves this — worth a sentence in the paper.
- **To strengthen results for the camera-ready:** set `DS=10`, `ROUNDS=40`; optionally average metrics over several `SEED`s and report mean±std.
"""

import matplotlib.pyplot as plt
import networkx as nx
import matplotlib.patches as mpatches
import numpy as np

# 1. Initialize the graph & edges
G = nx.Graph()
ieee_39_edges = [
    (1, 2), (1, 39), (2, 3), (2, 25), (2, 30), (3, 4), (3, 18), (4, 5), (4, 14),
    (5, 6), (5, 8), (6, 7), (6, 11), (6, 31), (7, 8), (8, 9), (9, 39), (10, 11), (10, 13),
    (10, 32), (11, 12), (12, 13), (13, 14), (14, 15), (15, 16), (16, 17), (16, 19),
    (16, 21), (16, 24), (17, 18), (17, 27), (19, 20), (19, 33), (20, 34), (21, 22),
    (22, 23), (22, 35), (23, 24), (23, 36), (25, 26), (25, 37), (26, 27), (26, 28),
    (26, 29), (28, 29), (29, 38)
]
G.add_edges_from(ieee_39_edges)

# 2. Define Manual Layout (Standard IEEE 39-Bus Shape)
manual_pos = {
    39: (0, 8), 9: (0, 6), 8: (0, 4), 7: (0, 2),
    1: (2, 8), 2: (4, 8), 25: (6, 8), 26: (8, 8), 28: (9, 8.5), 29: (10, 8),
    30: (4, 9), 37: (6, 9), 38: (10, 9),
    27: (8, 6.5),
    3: (4, 6), 18: (6, 6), 17: (8, 5.5),
    4: (4, 4), 14: (6, 4), 15: (7, 4), 16: (8, 4),
    5: (2, 4),
    6: (2, 2), 31: (1, 2),
    11: (4, 2), 12: (6, 2), 13: (5, 3),
    10: (4, 0), 32: (4, -1),
    19: (9, 5), 20: (10, 5), 33: (9, 6), 34: (11, 5),
    21: (8, 2), 22: (10, 2), 35: (11, 2),
    23: (10, 0), 36: (10, -1),
    24: (9, 3)
}

fig, ax = plt.subplots(figsize=(20, 15))

# 3. Draw standard base network
nx.draw_networkx_edges(G, manual_pos, edge_color='gray', width=2, ax=ax)
# Draw all 39 buses clearly as squares
nx.draw_networkx_nodes(G, manual_pos, node_shape='s', node_color='lightgray', node_size=800, edgecolors='black', ax=ax)

# Bus labels (custom offsets to avoid overlapping with transmission lines)
custom_label_offsets = {
    39: (-0.4, 0.4), 9: (-0.4, 0), 8: (-0.4, 0), 7: (-0.4, 0),
    1: (0, 0.4), 2: (-0.4, 0.4), 25: (-0.4, 0.4), 26: (0, 0.4), 28: (-0.5, 0.5), 29: (0.4, -0.4),
    30: (-0.7, 0), 37: (-0.7, 0), 38: (0.5, -0.5),
    27: (-0.5, 0.5), 3: (-0.4, 0.4), 18: (0.5, -0.5), 17: (-0.4, 0.4),
    4: (0.4, 0.4), 14: (0, 0.4), 15: (0, 0.4), 16: (-0.4, -0.4),
    5: (0, 0.4), 6: (0.4, 0.4), 31: (0, 0.4),
    11: (-0.4, 0.4), 12: (0, 0.4), 13: (0, 0.4),
    10: (-0.4, 0), 32: (-0.7, 0),
    19: (0.5, -0.5), 20: (0.4, 0.4), 33: (0.7, 0), 34: (0, 0.4),
    21: (-0.7, 0), 22: (0.4, 0.4), 35: (0, 0.4),
    23: (-0.7, -0.4), 36: (-0.7, 0), 24: (0.5, 0.5)
}
label_pos = {k: (v[0] + custom_label_offsets.get(k, (0, 0.35))[0], v[1] + custom_label_offsets.get(k, (0, 0.35))[1]) for k, v in manual_pos.items()}

nx.draw_networkx_labels(G, label_pos, font_size=26, font_weight='bold', ax=ax,
                        bbox=dict(facecolor='white', edgecolor='none', alpha=0.9, pad=0.2))

# 4. Draw Generators attached to the buses (preventing overlap)
generators = {30: 'G1', 31: 'G2', 32: 'G3', 33: 'G4', 34: 'G5', 35: 'G6', 36: 'G7', 37: 'G8', 38: 'G9', 39: 'G10'}
# Define outward offsets for the generators so they extend outward from the bus node
gen_offsets = {
    30: (0, 0.9), 31: (0, -0.9), 32: (0, -0.9), 33: (0, 0.9), 34: (0.9, 0),
    35: (0.9, 0), 36: (0.9, 0), 37: (0, 0.9), 38: (0.9, 0), 39: (-0.9, 0)
}

for gen_node, gen_name in generators.items():
    bx, by = manual_pos[gen_node]
    dx, dy = gen_offsets.get(gen_node, (0, 0.9))
    gx, gy = bx + dx, by + dy

    # Connect generator to bus
    ax.plot([bx, gx], [by, gy], color='black', lw=1.5, zorder=2)

    # Draw generator circle
    circle = plt.Circle((gx, gy), 0.45, color='white', ec='black', lw=1.5, zorder=5)
    ax.add_patch(circle)
    ax.text(gx, gy, gen_name, fontsize=24, fontweight='bold', ha='center', va='center', zorder=6)

# 5. Helper function for DC boxes (reduced pad and font size)
def draw_dc_box(ax, x, y, text, color):
    bbox_props = dict(boxstyle="round,pad=0.3", fc=color, ec="black", lw=1.5, alpha=0.9)
    ax.text(x, y, text, ha="center", va="center", size=22, weight='bold', bbox=bbox_props, zorder=10)

# 6. Place Data Centers using the manual coordinates
# Moving them into guaranteed free space based on the grid above

# DC1 (Bus 4 at 4,4) -> Move up-left to (2, 5.5)
draw_dc_box(ax, manual_pos[4][0] - 2.0, manual_pos[4][1] + 1.5, "DC1\n(~350 MW)", "lightcoral")
ax.annotate("", xy=manual_pos[4], xytext=(manual_pos[4][0] - 1.8, manual_pos[4][1] + 1.3), arrowprops=dict(arrowstyle="->", color="red", lw=2.0), zorder=9)

# DC2 (Bus 23 at 10,0) -> Move vertically between G6 and G7
draw_dc_box(ax, 12.0, 0.5, "DC2\n(~200 MW)", "navajowhite")
ax.annotate("", xy=manual_pos[23], xytext=(11.8, 0.5), arrowprops=dict(arrowstyle="->", color="orange", lw=2.0), zorder=9)

# DC3 (Bus 18 at 6,6) -> Move up-left to (5, 7.2) to avoid buses 6 and 14 entirely
draw_dc_box(ax, manual_pos[18][0] - 1.0, manual_pos[18][1] + 1.2, "DC3\n(~150 MW)", "plum")
ax.annotate("", xy=manual_pos[18], xytext=(manual_pos[18][0] - 0.8, manual_pos[18][1] + 1.0), arrowprops=dict(arrowstyle="->", color="purple", lw=2.0), zorder=9)

# DC4 (Bus 16 at 8,4) -> Move vertically between G5 and G6
draw_dc_box(ax, 11.5, 3.5, "DC4\n(~300 MW)", "lightskyblue")
ax.annotate("", xy=manual_pos[16], xytext=(11.3, 3.5), arrowprops=dict(arrowstyle="->", color="blue", lw=2.0), zorder=9)

# Center the full figure by explicitly setting symmetrical limits
ax.set_xlim(-2.0, 14.0)
ax.set_ylim(-3.0, 11.0)

plt.axis('off')
plt.tight_layout()
plt.savefig("IEEE_39_Bus_DC_Final_Paper.pdf", format="pdf", bbox_inches='tight', pad_inches=0)
print("Figure successfully saved as 'IEEE_39_Bus_DC_Final_Paper.pdf'")
plt.show()